### ISSUE TITLE
android app for mom

### ISSUE THREAD

**Issue by bhaskar4n** [kvsankar/mom#1]
i am bhaskaran. your website "http://sankara.net/" is good and informative about mars orbiter mission and  i have created an android application about "mars orbiter mission" to track current status similar to your website. for that i have collected jpl horizons Ephemeris  data.  Did i need permission from jpl to publish my application?. if yes, how to get permission. 
![momsc](https://cloud.githubusercontent.com/assets/6498891/3718115/a508238e-1631-11e4-959b-12e32fa7497c.png)
                           Thank you...  

https://github.com/bhaskar4n/mom

https://raw.githubusercontent.com/bhaskar4n/mom/master/Screenshot_2014-07-28-13-13-34.png

**Comment by kvsankar** [comment]
You don't need any permissions from NASA JPL just to use their ephemeris
data.

**Comment by bhaskar4n** [comment]
Thank you for your reply..
