### ISSUE TITLE
Regarding chandrayaan-2 animation. 

### ISSUE THREAD

**Issue by bhaskar4n** [kvsankar/mom#3]
Nice animation sir,

For this date and time **(2019-Aug-02 00:11:00.0000)**, your Chandrayaan-2 animation showing information based on this date **2019-Aug-01 18:41:00.0000** TDB(around 5 hrs variation.)
**chandrayaan-2 vectors data**:
**2458697.278472222 = A.D. 2019-Aug-01 18:41:00.0000 TDB** 
X = 7.336345604451427E+04 Y = 1.472680171014254E+04 Z =-8.056875454781390E+03
VX= 3.237636262362991E-01 VY= 1.010539535291576E+00 VZ=-8.057693839304275E-02
r= sqrt(X*X+y*y+z*z) =  75259.4752406572 km(chandrayaan-2 distance relative to center of Earth)

when i checked the horizons data for this date and time **(2019-Aug-02 00:11:00.0000)**, it showing this data
**chandrayaan-2 vectors data**:
**2458697.507638889 = A.D. 2019-Aug-02 00:11:00.0000 TDB** 
X = 6.713389284881664E+04 Y = 3.114839058227488E+04 Z =-8.214159425535774E+03
VX=-9.409444654659901E-01 VY= 5.964315978452236E-01 VZ= 6.594436973605297E-02
r= sqrt(x*x+y*y+z*z) = 74462.43495864517 km(chandrayaan-2 distance relative to center of Earth)

why this variation(around 5hrs)? 
  
......................................................................................
my horizons data and its settings.
......................................................................................

Ephemeris Type [change] : 	VECTORS
Target Body [change] : 	Chandrayaan-2 (spacecraft) (CH-2=CH2) [-152]
Coordinate Origin [change] : 	Geocentric [500]
Time Span [change] : 	Start=2019-07-22 09:31, Stop=2019-08-20 00:00, Step=1 m
Table Settings [change] : 	quantities code=2; output units=KM-S
Display/Output [change] : 	download/save (plain text file)
.......................................................................................

i have checked chandrayaan-2 vectors only
if iam wrong, please ignore this message.

**Comment by kvsankar** [comment]
The MOM animation has not been updated in ages. The animation was valid only from the MOM launch date until Martian entry. I probably would have to indicate this somewhere on the animation. Thanks!

**Comment by bhaskar4n** [comment]
Thanks for your response.

I think, i have found it.
UTC+05:30 = IST
2019-Aug-01 18:41 + 05:30 =  2019-Aug-02 00:11:00.

Thank you.
